### ISSUE TITLE
Build Failed with the module

### ISSUE THREAD

**Issue by ronywix** [hansemannn/titanium-google-signin#13]
Hi,
I can't build when including the module in tiapp.xml
I get the following error:
Ld build/Products/Debug-iphonesimulator/ShoutOut.app/ShoutOut normal x86_64

Maybe it's related to the fact that CLI update (Appcelerator CLI 6.2.3.GA ) is failing?

This is the CLI update fail error:
Error encountered during update
Failed to get value of npm config key prefix: module.js:327
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Anyway, all other modules are built well

I will appreciate a quick help

Rony

**Comment by hansemannn** [comment]
Please attach a trace-log (`appc run -p ios --log-level trace`).

**Comment by ronywix** [comment]
I'm not sure about that.
I get all unrelated errors (smae without including this module), but when i run from IDE, without the module it builds, with it, i get 

> Ld build/Products/Debug-iphonesimulator/googlesigninTest.app/googlesigninTest normal x86_64

The module has no build.py, and the default build settings gives me the same result

**Comment by hansemannn** [comment]
It does not have a build.py because devs use `appc run -p ios --build-only` these days to trigger the build. Try it out or just grab a release from the **Releases** tab, thx!
